/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    user: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    upload: Upload;
    page: Page;
    user: User;
    post: Post;
    category: Category;
    project: Project;
    term: Term;
    service: Service;
    'calculator-results': CalculatorResult;
    forms: Form;
    'form-submissions': FormSubmission;
    redirects: Redirect;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'calculator-results': {
      formSubmissions: 'form-submissions';
    };
  };
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    upload: UploadSelect<false> | UploadSelect<true>;
    page: PageSelect<false> | PageSelect<true>;
    user: UserSelect<false> | UserSelect<true>;
    post: PostSelect<false> | PostSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    term: TermSelect<false> | TermSelect<true>;
    service: ServiceSelect<false> | ServiceSelect<true>;
    'calculator-results': CalculatorResultsSelect<false> | CalculatorResultsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    settings: Settings;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'user';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sq?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload".
 */
export interface Upload {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page".
 */
export interface Page {
  id: string;
  slug?: string | null;
  pathname?: string | null;
  containerSize?: ('default' | 'post') | null;
  enableBreadcrumbs?: boolean | null;
  parent?: (string | null) | Page;
  hero?: PageHero;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * This will be displayed as the title in search engine results
     */
    title?: string | null;
    /**
     * This will be displayed as the description in search engine results
     */
    description?: string | null;
    /**
     * This image will be used when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * The canonical URL for this page. Leave empty to use the default URL.
     */
    canonicalURL?: string | null;
    /**
     * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
     */
    noIndex?: boolean | null;
  };
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHero".
 */
export interface PageHero {
  type?: ('standard' | 'primary') | null;
  primary?: {
    prefix?: string | null;
    suffix?: string | null;
    cover?: (string | null) | Media;
    images?: (string | Media)[] | null;
  };
  default?: {
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user".
 */
export interface User {
  id: string;
  roles: ('admin' | 'editor')[];
  name?: string | null;
  job?: string | null;
  picture?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post".
 */
export interface Post {
  id: string;
  slug?: string | null;
  publishedAt?: string | null;
  author?: (string | null) | User;
  categories?: (string | Category)[] | null;
  title: string;
  cover?: (string | null) | Media;
  /**
   * Image that will be displayed at the top of the post page. If not set, the cover image will be used.
   */
  headerImage?: (string | null) | Media;
  /**
   * If unchecked, no image will be displayed at the top of the post page.
   */
  showHeaderImage?: boolean | null;
  /**
   * Choose how the header image should be displayed.
   */
  headerImageMode?: ('cover' | 'contain') | null;
  /**
   * A short preview of the content, typically shown in lists and search results.
   */
  excerpt?: string | null;
  article?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * This will be displayed as the title in search engine results
     */
    title?: string | null;
    /**
     * This will be displayed as the description in search engine results
     */
    description?: string | null;
    /**
     * This image will be used when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * The canonical URL for this page. Leave empty to use the default URL.
     */
    canonicalURL?: string | null;
    /**
     * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: string;
  name?: string | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: string;
  _order?: string | null;
  slug?: string | null;
  title: string;
  suffix?: string | null;
  cover?: (string | null) | Media;
  description?: {
    title?: string | null;
    subtitle?: string | null;
    text?: string | null;
    planOne?: (string | null) | Media;
    planTwo?: (string | null) | Media;
  };
  /**
   * Cover image for project card preview
   */
  cardCover?: (string | null) | Media;
  /**
   * A short preview of the content, typically shown in lists and search results.
   */
  excerpt?: string | null;
  article?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * This will be displayed as the title in search engine results
     */
    title?: string | null;
    /**
     * This will be displayed as the description in search engine results
     */
    description?: string | null;
    /**
     * This image will be used when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * The canonical URL for this page. Leave empty to use the default URL.
     */
    canonicalURL?: string | null;
    /**
     * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "term".
 */
export interface Term {
  id: string;
  slug?: string | null;
  showHero?: boolean | null;
  title: string;
  cardTitle: string;
  suffix?: string | null;
  cover?: (string | null) | Media;
  /**
   * A short preview of the content, typically shown in lists and search results.
   */
  excerpt?: string | null;
  article?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * This will be displayed as the title in search engine results
     */
    title?: string | null;
    /**
     * This will be displayed as the description in search engine results
     */
    description?: string | null;
    /**
     * This image will be used when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * The canonical URL for this page. Leave empty to use the default URL.
     */
    canonicalURL?: string | null;
    /**
     * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service".
 */
export interface Service {
  id: string;
  slug?: string | null;
  title: string;
  cardTitle: string;
  suffix?: string | null;
  cover?: (string | null) | Media;
  /**
   * A short preview of the content, typically shown in lists and search results.
   */
  excerpt?: string | null;
  article?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    /**
     * This will be displayed as the title in search engine results
     */
    title?: string | null;
    /**
     * This will be displayed as the description in search engine results
     */
    description?: string | null;
    /**
     * This image will be used when sharing on social media
     */
    image?: (string | null) | Media;
    /**
     * The canonical URL for this page. Leave empty to use the default URL.
     */
    canonicalURL?: string | null;
    /**
     * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-results".
 */
export interface CalculatorResult {
  id: string;
  calculationNumber?: string | null;
  clientName?: string | null;
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    /**
     * ID чата клиента для отправки PDF через Telegram
     */
    telegramChatId?: string | null;
  };
  /**
   * Итоговые данные расчета
   */
  calculationSummary?: {
    area?: number | null;
    selectedFloor?: string | null;
    totalCost?: number | null;
  };
  selectedServices?: string | null;
  additionalElements?: string | null;
  /**
   * Все данные расчета в JSON формате для генерации PDF
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  formSubmissions?: {
    docs?: (string | FormSubmission)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  sendToTelegram?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  calculatorResult?: (string | null) | CalculatorResult;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            description?: string | null;
            width?: number | null;
            defaultValue?: boolean | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'upload';
          }
        | {
            name: string;
            label?: string | null;
            placeholder?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            options: {
              label: string;
              value: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'radio';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message, or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This can be overridden when placing the form on a page
   */
  showTitle?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * The relative path to redirect from (e.g., /old-page or /post/old-slug)
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'page';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'post';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'service';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'project';
          value: string | Project;
        } | null)
      | ({
          relationTo: 'category';
          value: string | Category;
        } | null)
      | ({
          relationTo: 'term';
          value: string | Term;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'upload';
        value: string | Upload;
      } | null)
    | ({
        relationTo: 'page';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'user';
        value: string | User;
      } | null)
    | ({
        relationTo: 'post';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'category';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'project';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'term';
        value: string | Term;
      } | null)
    | ({
        relationTo: 'service';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'calculator-results';
        value: string | CalculatorResult;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'user';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'user';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sq?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload_select".
 */
export interface UploadSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page_select".
 */
export interface PageSelect<T extends boolean = true> {
  slug?: T;
  pathname?: T;
  containerSize?: T;
  enableBreadcrumbs?: T;
  parent?: T;
  hero?: T | PageHeroSelect<T>;
  title?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHero_select".
 */
export interface PageHeroSelect<T extends boolean = true> {
  type?: T;
  primary?:
    | T
    | {
        prefix?: T;
        suffix?: T;
        cover?: T;
        images?: T;
      };
  default?:
    | T
    | {
        richText?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_select".
 */
export interface UserSelect<T extends boolean = true> {
  roles?: T;
  name?: T;
  job?: T;
  picture?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post_select".
 */
export interface PostSelect<T extends boolean = true> {
  slug?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  title?: T;
  cover?: T;
  headerImage?: T;
  showHeaderImage?: T;
  headerImageMode?: T;
  excerpt?: T;
  article?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  _order?: T;
  slug?: T;
  title?: T;
  suffix?: T;
  cover?: T;
  description?:
    | T
    | {
        title?: T;
        subtitle?: T;
        text?: T;
        planOne?: T;
        planTwo?: T;
      };
  cardCover?: T;
  excerpt?: T;
  article?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "term_select".
 */
export interface TermSelect<T extends boolean = true> {
  slug?: T;
  showHero?: T;
  title?: T;
  cardTitle?: T;
  suffix?: T;
  cover?: T;
  excerpt?: T;
  article?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service_select".
 */
export interface ServiceSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  cardTitle?: T;
  suffix?: T;
  cover?: T;
  excerpt?: T;
  article?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonicalURL?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-results_select".
 */
export interface CalculatorResultsSelect<T extends boolean = true> {
  calculationNumber?: T;
  clientName?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        telegramChatId?: T;
      };
  calculationSummary?:
    | T
    | {
        area?: T;
        selectedFloor?: T;
        totalCost?: T;
      };
  selectedServices?: T;
  additionalElements?: T;
  metadata?: T;
  notes?: T;
  formSubmissions?: T;
  sendToTelegram?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              description?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        upload?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        radio?:
          | T
          | {
              name?: T;
              label?: T;
              placeholder?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  showTitle?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  calculatorResult?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: string;
  company?: {
    name?: string | null;
  };
  navigation?: {
    header?: {
      links?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'page';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'service';
                    value: string | Service;
                  } | null)
                | ({
                    relationTo: 'term';
                    value: string | Term;
                  } | null)
                | ({
                    relationTo: 'post';
                    value: string | Post;
                  } | null);
              url?: string | null;
              label: string;
            };
            id?: string | null;
          }[]
        | null;
    };
    footer?: {
      links?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'page';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'service';
                    value: string | Service;
                  } | null)
                | ({
                    relationTo: 'term';
                    value: string | Term;
                  } | null)
                | ({
                    relationTo: 'post';
                    value: string | Post;
                  } | null);
              url?: string | null;
              label: string;
            };
            id?: string | null;
          }[]
        | null;
      copyText?: string | null;
      legalLinks?:
        | {
            link: {
              type?: ('reference' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'page';
                    value: string | Page;
                  } | null)
                | ({
                    relationTo: 'service';
                    value: string | Service;
                  } | null)
                | ({
                    relationTo: 'term';
                    value: string | Term;
                  } | null)
                | ({
                    relationTo: 'post';
                    value: string | Post;
                  } | null);
              url?: string | null;
              label: string;
            };
            id?: string | null;
          }[]
        | null;
    };
  };
  seo?: {
    default?: {
      /**
       * This will be displayed as the title in search engine results
       */
      title?: string | null;
      /**
       * This will be displayed as the description in search engine results
       */
      description?: string | null;
      /**
       * This image will be used when sharing on social media
       */
      image?: (string | null) | Media;
      /**
       * The canonical URL for this page. Leave empty to use the default URL.
       */
      canonicalURL?: string | null;
      /**
       * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
       */
      noIndex?: boolean | null;
    };
    blog?: {
      /**
       * This will be displayed as the title in search engine results
       */
      title?: string | null;
      /**
       * This will be displayed as the description in search engine results
       */
      description?: string | null;
      /**
       * This image will be used when sharing on social media
       */
      image?: (string | null) | Media;
      /**
       * The canonical URL for this page. Leave empty to use the default URL.
       */
      canonicalURL?: string | null;
      /**
       * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
       */
      noIndex?: boolean | null;
    };
    calculator?: {
      /**
       * This will be displayed as the title in search engine results
       */
      title?: string | null;
      /**
       * This will be displayed as the description in search engine results
       */
      description?: string | null;
      /**
       * This image will be used when sharing on social media
       */
      image?: (string | null) | Media;
      /**
       * The canonical URL for this page. Leave empty to use the default URL.
       */
      canonicalURL?: string | null;
      /**
       * Checking this box will add meta tags to the page, asking search engines not to index this page. It will also remove it from the sitemap.
       */
      noIndex?: boolean | null;
    };
  };
  calculator: {
    calculatorTitle: string;
    currency: string;
    areaSettings?: {
      label?: string | null;
      placeholder?: string | null;
      defaultArea?: number | null;
      description?: string | null;
      areaCoefficients?:
        | {
            label: string;
            minArea: number;
            maxArea?: number | null;
            coefficient: number;
            id?: string | null;
          }[]
        | null;
    };
    floorSettings?: {
      label?: string | null;
      floorOptions?:
        | {
            name: string;
            coefficient: number;
            isDefault?: boolean | null;
            id?: string | null;
          }[]
        | null;
    };
    servicesSections?:
      | {
          title: string;
          services?:
            | {
                name?: string | null;
                fieldType?: ('radio' | 'checkbox') | null;
                pricePerM2?: number | null;
                fixedPrice?: number | null;
                description?: {
                  root: {
                    type: string;
                    children: {
                      type: string;
                      version: number;
                      [k: string]: unknown;
                    }[];
                    direction: ('ltr' | 'rtl') | null;
                    format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                    indent: number;
                    version: number;
                  };
                  [k: string]: unknown;
                } | null;
                ignoreArea?: boolean | null;
                isRequired?: boolean | null;
                isDefault?: boolean | null;
                /**
                 * Для группировки радио кнопок (например: "opr-group")
                 */
                radioGroup?: string | null;
                /**
                 * При выборе этой услуги появятся дополнительные варианты
                 */
                hasOptions?: boolean | null;
                options?:
                  | {
                      name: string;
                      pricePerM2?: number | null;
                      description?: {
                        root: {
                          type: string;
                          children: {
                            type: string;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      } | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    additionalSections?:
      | {
          title: string;
          fieldType?: ('checkbox' | 'radio') | null;
          elements?:
            | {
                name: string;
                price: number;
                isDefault?: boolean | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    interfaceTexts?: {
      submitButtonText?: string | null;
      resetButtonText?: string | null;
      totalPriceLabel?: string | null;
      pricePerM2Label?: string | null;
      additionalElementsTitle?: string | null;
    };
    resultPageSettings?: {
      /**
       * Form that will be displayed on the calculator result page
       */
      resultForm?: (string | null) | Form;
      formShowButtonText?: string | null;
      formHideButtonText?: string | null;
      downloadPdfButtonText?: string | null;
      downloadPdfButtonLoading?: string | null;
      shareButtonText?: string | null;
      shareToTelegramButtonText?: string | null;
    };
    instructions?: {
      title?: string | null;
      steps?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    pdfSuffixContent?: {
      title?: string | null;
      /**
       * This content will appear after the totals section in the PDF
       */
      content?: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  company?:
    | T
    | {
        name?: T;
      };
  navigation?:
    | T
    | {
        header?:
          | T
          | {
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
        footer?:
          | T
          | {
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              copyText?: T;
              legalLinks?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
            };
      };
  seo?:
    | T
    | {
        default?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              canonicalURL?: T;
              noIndex?: T;
            };
        blog?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              canonicalURL?: T;
              noIndex?: T;
            };
        calculator?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              canonicalURL?: T;
              noIndex?: T;
            };
      };
  calculator?:
    | T
    | {
        calculatorTitle?: T;
        currency?: T;
        areaSettings?:
          | T
          | {
              label?: T;
              placeholder?: T;
              defaultArea?: T;
              description?: T;
              areaCoefficients?:
                | T
                | {
                    label?: T;
                    minArea?: T;
                    maxArea?: T;
                    coefficient?: T;
                    id?: T;
                  };
            };
        floorSettings?:
          | T
          | {
              label?: T;
              floorOptions?:
                | T
                | {
                    name?: T;
                    coefficient?: T;
                    isDefault?: T;
                    id?: T;
                  };
            };
        servicesSections?:
          | T
          | {
              title?: T;
              services?:
                | T
                | {
                    name?: T;
                    fieldType?: T;
                    pricePerM2?: T;
                    fixedPrice?: T;
                    description?: T;
                    ignoreArea?: T;
                    isRequired?: T;
                    isDefault?: T;
                    radioGroup?: T;
                    hasOptions?: T;
                    options?:
                      | T
                      | {
                          name?: T;
                          pricePerM2?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        additionalSections?:
          | T
          | {
              title?: T;
              fieldType?: T;
              elements?:
                | T
                | {
                    name?: T;
                    price?: T;
                    isDefault?: T;
                    id?: T;
                  };
              id?: T;
            };
        interfaceTexts?:
          | T
          | {
              submitButtonText?: T;
              resetButtonText?: T;
              totalPriceLabel?: T;
              pricePerM2Label?: T;
              additionalElementsTitle?: T;
            };
        resultPageSettings?:
          | T
          | {
              resultForm?: T;
              formShowButtonText?: T;
              formHideButtonText?: T;
              downloadPdfButtonText?: T;
              downloadPdfButtonLoading?: T;
              shareButtonText?: T;
              shareToTelegramButtonText?: T;
            };
        instructions?:
          | T
          | {
              title?: T;
              steps?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
        pdfSuffixContent?:
          | T
          | {
              title?: T;
              content?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlockType".
 */
export interface AccordionBlockType {
  items?:
    | {
        title?: string | null;
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlockType".
 */
export interface ArchiveBlockType {
  type?: 'project' | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlockType".
 */
export interface ButtonBlockType {
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'page';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'service';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'term';
                value: string | Term;
              } | null)
            | ({
                relationTo: 'post';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered
           */
          appearance?: ('default' | 'secondary' | 'outline' | 'ghost' | 'link' | 'black' | 'white') | null;
          size?: ('sm' | 'md' | 'lg' | 'xl') | null;
          icon?: ('none' | 'arrowRight' | 'arrowLeft') | null;
        };
        id?: string | null;
      }[]
    | null;
  settings?: {
    marginTop?: {
      mobile?: number | null;
      tablet?: number | null;
      desktop?: number | null;
    };
    marginBottom?: {
      mobile?: number | null;
      tablet?: number | null;
      desktop?: number | null;
    };
    align?: {
      mobile?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
      tablet?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
      desktop?: ('none' | 'left' | 'center' | 'right' | 'fullWidth') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardDownloadBlockType".
 */
export interface CardDownloadBlockType {
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'page';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'service';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'term';
          value: string | Term;
        } | null)
      | ({
          relationTo: 'post';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardDownload';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardLinkBlockType".
 */
export interface CardLinkBlockType {
  image?: (string | null) | Media;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'page';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'service';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'term';
          value: string | Term;
        } | null)
      | ({
          relationTo: 'post';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardLink';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlockType".
 */
export interface CalloutBlockType {
  text?: string | null;
  settings?: {
    margin?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlockType".
 */
export interface CarouselBlockType {
  images?: (string | Media)[] | null;
  settings?: {
    enableDots?: boolean | null;
    enableThumbnails?: boolean | null;
    enableLoop?: boolean | null;
    enableArrows?: boolean | null;
    format?: ('cover' | 'contain') | null;
    mainImageFormat?: ('cover' | 'contain') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselFullBlockType".
 */
export interface CarouselFullBlockType {
  useTabs?: boolean | null;
  /**
   * Add tabs to organize your content
   */
  tabs?:
    | {
        label: string;
        images?: (string | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  images?: (string | Media)[] | null;
  settings?: {
    enableDots?: boolean | null;
    enableThumbnails?: boolean | null;
    enableLoop?: boolean | null;
    enableArrows?: boolean | null;
    enableGrid?: boolean | null;
    aspectRatio?: ('video' | 'square' | 'fourThree') | null;
    gridConfig?: {
      desktopColumns: '2' | '3' | '4';
      tabletColumns: '2' | '3';
      mobileColumns: '1' | '2';
      gap?: ('none' | 'two' | 'four' | 'eight') | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'carouselFull';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactInfoBlockType".
 */
export interface ContactInfoBlockType {
  image?: (string | null) | Media;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?: {
    whatsapp?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'service';
            value: string | Service;
          } | null)
        | ({
            relationTo: 'term';
            value: string | Term;
          } | null)
        | ({
            relationTo: 'post';
            value: string | Post;
          } | null);
      url?: string | null;
    };
    telegram?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'service';
            value: string | Service;
          } | null)
        | ({
            relationTo: 'term';
            value: string | Term;
          } | null)
        | ({
            relationTo: 'post';
            value: string | Post;
          } | null);
      url?: string | null;
    };
    email?: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'page';
            value: string | Page;
          } | null)
        | ({
            relationTo: 'service';
            value: string | Service;
          } | null)
        | ({
            relationTo: 'term';
            value: string | Term;
          } | null)
        | ({
            relationTo: 'post';
            value: string | Post;
          } | null);
      url?: string | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactInfo';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlockType".
 */
export interface ImageBlockType {
  image?: (string | null) | Media;
  aspectRatio?: ('video' | 'square' | 'fourThree') | null;
  format?: ('cover' | 'contain') | null;
  scale?: number | null;
  lightbox?: boolean | null;
  alignment?: ('left' | 'center' | 'right') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContainerBlockType".
 */
export interface ContainerBlockType {
  textLeft?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textRight?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  enableSize?: ('third' | 'twofifths' | 'half' | 'twothirds' | 'threefourths' | 'fourfifths' | 'fivesixths') | null;
  settings?: {
    gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    verticalAlign?: ('none' | 'top' | 'center' | 'bottom') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'container';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DoubleFormBlockType".
 */
export interface DoubleFormBlockType {
  forms?:
    | {
        form: string | Form;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'page';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'service';
                value: string | Service;
              } | null)
            | ({
                relationTo: 'term';
                value: string | Term;
              } | null)
            | ({
                relationTo: 'post';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'doubleForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SingleFormBlockType".
 */
export interface SingleFormBlockType {
  form: string | Form;
  id?: string | null;
  blockName?: string | null;
  blockType: 'singleForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EmbedBlockType".
 */
export interface EmbedBlockType {
  code: string;
  landscapeVideo?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'embed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeographyBlockType".
 */
export interface GeographyBlockType {
  textLeft?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  textRight?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  enableBorder?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'geography';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnerBlockType".
 */
export interface PartnerBlockType {
  image?: (string | null) | Media;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PriceBlockType".
 */
export interface PriceBlockType {
  title?: string | null;
  prices?:
    | {
        price?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'page';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'service';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'term';
          value: string | Term;
        } | null)
      | ({
          relationTo: 'post';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'price';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsBlockType".
 */
export interface ProjectsBlockType {
  count?: number | null;
  link: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'page';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'service';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'term';
          value: string | Term;
        } | null)
      | ({
          relationTo: 'post';
          value: string | Post;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'projects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlockType".
 */
export interface TableBlockType {
  /**
   * Select the number of columns (1-5)
   */
  columns: number;
  withHeader?: boolean | null;
  headerColOne?: string | null;
  headerColTwo?: string | null;
  headerColThree?: string | null;
  headerColFour?: string | null;
  headerColFive?: string | null;
  rows?:
    | {
        col1?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        col2?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        col3?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        col4?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        col5?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'table';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GridBlockType".
 */
export interface GridBlockType {
  useTabs?: boolean | null;
  /**
   * Add tabs to organize your content
   */
  tabs?:
    | {
        label: string;
        /**
         * Add items to this tab
         */
        items?:
          | {
              content?: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              settings?: {
                horizontalAlign?: ('none' | 'left' | 'center' | 'right') | null;
                verticalAlign?: ('none' | 'top' | 'center' | 'bottom') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        settings?: {
          horizontalAlign?: ('none' | 'left' | 'center' | 'right') | null;
          verticalAlign?: ('none' | 'top' | 'center' | 'bottom') | null;
        };
        id?: string | null;
      }[]
    | null;
  settings?: {
    margin?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    gap?: ('none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    verticalAlign?: ('none' | 'top' | 'center' | 'bottom') | null;
    columns?: {
      mobile?: ('1' | '2' | '3' | '4' | '6' | '12') | null;
      tablet?: ('1' | '2' | '3' | '4' | '6' | '12') | null;
      desktop?: ('1' | '2' | '3' | '4' | '6' | '12') | null;
    };
    fullWidth?: {
      mobile?: boolean | null;
      tablet?: boolean | null;
      desktop?: boolean | null;
    };
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'grid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}